### ISSUE TITLE
have no #include "ui_panelsettingswidget.h"

### ISSUE THREAD

**Issue by xinsuinizhuan** [iwxyi/FloatingUniverse#1]
![图片](https://user-images.githubusercontent.com/40679769/165198546-2ebef6d9-089a-44bb-83bc-78787ea8d095.png)

**Comment by iwxyi** [comment]
第一次打开时编译一下就会自动生成了

**Comment by xinsuinizhuan** [comment]
Qt打开，VS编译器或者mingw32编译器，都会很多报错。没法编译。

**Comment by iwxyi** [comment]
只能用 Qt Creator 打开 .pro 文件，否则肯定是编译不了的

**Comment by iwxyi** [comment]
MinGW 应该能用的啊，你的报了什么错？
